
volumes:
  node_modules:
    driver: local


services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    restart: on-failure
    